// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-FjsEpFsmNDAAXqRXfFfNRc5rbncSUU',
    appId: '1:505107877321:web:181dca20d1b8e37cce6c18',
    messagingSenderId: '505107877321',
    projectId: 'dataazure-4ad63',
    authDomain: 'dataazure-4ad63.firebaseapp.com',
    storageBucket: 'dataazure-4ad63.firebasestorage.app',
    measurementId: 'G-KV64CJEJ7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYYxBVnkOQsKt7uyjT6ZNsB-tjmGOagE',
    appId: '1:505107877321:android:15ec99fdf87cb163ce6c18',
    messagingSenderId: '505107877321',
    projectId: 'dataazure-4ad63',
    storageBucket: 'dataazure-4ad63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcXSJ1vdfuxdFl4W8UUe1EULf1NTgLSqg',
    appId: '1:505107877321:ios:29f51651ff191682ce6c18',
    messagingSenderId: '505107877321',
    projectId: 'dataazure-4ad63',
    storageBucket: 'dataazure-4ad63.firebasestorage.app',
    iosBundleId: 'com.example.petConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcXSJ1vdfuxdFl4W8UUe1EULf1NTgLSqg',
    appId: '1:505107877321:ios:29f51651ff191682ce6c18',
    messagingSenderId: '505107877321',
    projectId: 'dataazure-4ad63',
    storageBucket: 'dataazure-4ad63.firebasestorage.app',
    iosBundleId: 'com.example.petConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX-FjsEpFsmNDAAXqRXfFfNRc5rbncSUU',
    appId: '1:505107877321:web:3a212fa20a2c6e9cce6c18',
    messagingSenderId: '505107877321',
    projectId: 'dataazure-4ad63',
    authDomain: 'dataazure-4ad63.firebaseapp.com',
    storageBucket: 'dataazure-4ad63.firebasestorage.app',
    measurementId: 'G-LHPZGX6461',
  );

}